import { Box, Text } from "ink";
import type { ReactNode } from "react";
import { compact, duration, tokens } from "./format/values.js";
import type { ActiveRun, Overrides } from "./types.js";

export function Header({ cwd, overrides }: { cwd: string; overrides: Overrides }) { const mode = overrides.mode ?? "auto"; return <Box borderStyle="round" paddingX={1}><Text bold>Dynamic Task Router</Text><Text> · {compact(cwd.split("/").filter(Boolean).pop() ?? "repository", 28)} · mode:{mode.toUpperCase()} · provider:{overrides.provider ?? "any"} · model:{overrides.modelId ?? "auto"} · effort:{overrides.effort ?? "auto"}</Text></Box>; }
export function Panel({ title, children }: { title: string; children: ReactNode }) { return <Box borderStyle="single" flexDirection="column" paddingX={1}><Text bold>{title}</Text>{children}</Box>; }
export function ProviderPanel({ providers, ollama }: { providers: Array<{ id: string; healthy: boolean; enabled: boolean; models: string[] }>; ollama?: { available: boolean; models: Array<{ name: string; runtimeSizeBytes?: number; contextLength?: number; expiresAt?: string }> } | undefined }) { return <Panel title="PROVIDERS">{providers.map((provider) => <Box key={provider.id} flexDirection="column"><Text>{provider.healthy ? "●" : provider.enabled ? "×" : "○"} {provider.id} · {provider.healthy ? "healthy" : provider.enabled ? "unavailable" : "disabled"} {provider.models.length ? `· ${provider.models.join(", ")}` : ""}</Text>{provider.id === "ollama" && ollama?.available && ollama.models.map((model) => <Text key={model.name}>  loaded: {model.name} · runtime size: {model.runtimeSizeBytes === undefined ? "unknown" : `${(model.runtimeSizeBytes / 1_000_000_000).toFixed(1)} GB`} · context: {model.contextLength ?? "unknown"}</Text>)}</Box>)}</Panel>; }
export function WorkerList({ runs }: { runs: ActiveRun[] }) { return <Panel title="ACTIVE RUNS">{runs.length ? runs.map((run) => <Text key={run.id}>{symbol(run.state)} {run.id.slice(0, 8)} · {compact(run.task)}{run.model ? ` · ${run.model}` : ""}{run.latest ? ` · ${compact(run.latest, 30)}` : ""}</Text>) : <Text>○ No active runs</Text>}</Panel>; }
export function ContextLine({ model, contextTokens, used }: { model: string; contextTokens: number; used?: number }) { return <Text>{model} · {used === undefined ? `window ${tokens(contextTokens)} · current usage unknown` : `${tokens(used)} / ${tokens(contextTokens)} (${Math.round((used / contextTokens) * 100)}%)`}</Text>; }
export function RunLine({ id, state, strategy, startedAt }: { id: string; state: string; strategy: string; startedAt: string }) { return <Text>{symbol(state)} {id.slice(0, 8)} · {strategy} · {state} · {new Date(startedAt).toLocaleString()}</Text>; }
export function StatusBar({ message }: { message?: string | undefined }) { return <Box borderStyle="single" paddingX={1}><Text>{message ?? "Ctrl+K dashboard · Ctrl+R runs · Ctrl+O models · Esc back · Up/Down history · /help commands"}</Text></Box>; }
export function Metric({ label, value, durationMs }: { label: string; value?: string | number; durationMs?: number }) { return <Text>{label}: {value ?? (durationMs === undefined ? "unavailable" : duration(durationMs))}</Text>; }
function symbol(state: string): string { if (state === "running") return "◐"; if (state === "succeeded" || state === "completed") return "✓"; if (state === "failed") return "×"; if (state === "aborted") return "↯"; if (state === "aborting") return "!"; return "○"; }
